"""-m add olt health monitoring columns to alert_rules

Revision ID: 0943f5af8d94
Revises: 
Create Date: 2026-07-10 01:02:23.703191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0943f5af8d94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('olt_id', sa.Integer(), nullable=True))
        batch_op.alter_column('onu_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_olt_offline', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('check_olt_cpu', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('check_olt_memory', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('check_olt_temperature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('olt_cpu_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('olt_memory_threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('olt_temp_threshold', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('bot_config', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('olt_pon_ports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sfp_vendor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sfp_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sfp_serial', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sfp_wavelength', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_connector', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_distance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_tx_power', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_rx_power', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_temperature', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_voltage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sfp_bias_current', sa.String(length=20), nullable=True))

    with op.batch_alter_table('olt_uplinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_vlan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ip_mask', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ip_gateway', sa.String(length=50), nullable=True))

    with op.batch_alter_table('olts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('onu_custom_columns', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('onus', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['technician_id'], ['id'])

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('tr069_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vlan_mode', sa.String(length=10), nullable=True))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tr069_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vlan_mode')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('onus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('onu_custom_columns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('olts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('olt_uplinks', schema=None) as batch_op:
        batch_op.drop_column('ip_gateway')
        batch_op.drop_column('ip_mask')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('ip_vlan_id')

    with op.batch_alter_table('olt_pon_ports', schema=None) as batch_op:
        batch_op.drop_column('sfp_bias_current')
        batch_op.drop_column('sfp_voltage')
        batch_op.drop_column('sfp_temperature')
        batch_op.drop_column('sfp_rx_power')
        batch_op.drop_column('sfp_tx_power')
        batch_op.drop_column('sfp_distance')
        batch_op.drop_column('sfp_connector')
        batch_op.drop_column('sfp_wavelength')
        batch_op.drop_column('sfp_serial')
        batch_op.drop_column('sfp_type')
        batch_op.drop_column('sfp_vendor')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bot_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('olt_temp_threshold')
        batch_op.drop_column('olt_memory_threshold')
        batch_op.drop_column('olt_cpu_threshold')
        batch_op.drop_column('check_olt_temperature')
        batch_op.drop_column('check_olt_memory')
        batch_op.drop_column('check_olt_cpu')
        batch_op.drop_column('check_olt_offline')

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.alter_column('onu_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('olt_id')

    # ### end Alembic commands ###
