"""baseline: current schema as of 2026-09-01

Revision ID: 2169e93c7970
Revises: 
Create Date: 2026-09-01 23:12:59.411797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2169e93c7970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.create_index('ix_action_logs_category', ['category'], unique=False)
        batch_op.create_index('ix_action_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_action_logs_user_id', ['user_id'], unique=False)

    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('last_value', sa.String(length=50), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index('ix_alert_history_olt_type', ['olt_id', 'alert_type'], unique=False)
        batch_op.create_index('ix_alert_history_onu_type', ['onu_id', 'alert_type'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('check_offline', sa.Boolean(), nullable=True),
    sa.Column('check_dyinggasp', sa.Boolean(), nullable=True),
    sa.Column('check_los', sa.Boolean(), nullable=True),
    sa.Column('check_rx_power', sa.Boolean(), nullable=True),
    sa.Column('rx_threshold', sa.Float(), nullable=True),
    sa.Column('rx_change_threshold', sa.Float(), nullable=True),
    sa.Column('check_olt_offline', sa.Boolean(), nullable=True),
    sa.Column('check_olt_cpu', sa.Boolean(), nullable=True),
    sa.Column('check_olt_memory', sa.Boolean(), nullable=True),
    sa.Column('check_olt_temperature', sa.Boolean(), nullable=True),
    sa.Column('olt_cpu_threshold', sa.Float(), nullable=True),
    sa.Column('olt_memory_threshold', sa.Float(), nullable=True),
    sa.Column('olt_temp_threshold', sa.Float(), nullable=True),
    sa.Column('notify_bell', sa.Boolean(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('notify_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('notify_whatsapp_native', sa.Boolean(), nullable=True),
    sa.Column('target_roles', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('bot_token', sa.String(length=512), nullable=True),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('api_url', sa.String(length=256), nullable=True),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ftth_fiber_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_type', sa.String(length=10), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_type', sa.String(length=10), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.Column('path_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('snmp_enabled', sa.Boolean(), nullable=True),
    sa.Column('snmp_community', sa.String(length=512), nullable=True),
    sa.Column('snmp_community_write', sa.String(length=512), nullable=True),
    sa.Column('snmp_port', sa.Integer(), nullable=True),
    sa.Column('telnet_enabled', sa.Boolean(), nullable=True),
    sa.Column('telnet_port', sa.Integer(), nullable=True),
    sa.Column('web_port', sa.Integer(), nullable=True),
    sa.Column('ssh_enabled', sa.Boolean(), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('cli_username', sa.String(length=100), nullable=True),
    sa.Column('cli_password', sa.String(length=512), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('polling_interval', sa.Integer(), nullable=True),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_backup_interval', sa.Integer(), nullable=True),
    sa.Column('auto_backup_unit', sa.String(length=10), nullable=True),
    sa.Column('auto_backup_time', sa.String(length=5), nullable=True),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('total_fan', sa.Integer(), nullable=True),
    sa.Column('total_onu', sa.Integer(), nullable=True),
    sa.Column('online_onu', sa.Integer(), nullable=True),
    sa.Column('los_onu', sa.Integer(), nullable=True),
    sa.Column('dyinggasp_onu', sa.Integer(), nullable=True),
    sa.Column('offline_onu', sa.Integer(), nullable=True),
    sa.Column('other_onu', sa.Integer(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('last_full_sync', sa.DateTime(), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=True),
    sa.Column('snmp_status', sa.String(length=20), nullable=True),
    sa.Column('telnet_status', sa.String(length=20), nullable=True),
    sa.Column('register_mode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onu_custom_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_key', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('visible_desktop', sa.Boolean(), nullable=True),
    sa.Column('visible_mobile', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('onu_type', sa.String(length=100), nullable=True),
    sa.Column('tcont_profile', sa.String(length=100), nullable=True),
    sa.Column('traffic_profile', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uptime_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('fan_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('speed_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ftth_otb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('pon_port', sa.String(length=50), nullable=True),
    sa.Column('total_cores', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_history', schema=None) as batch_op:
        batch_op.create_index('ix_metric_history_olt_type_time', ['olt_id', 'metric_type', 'recorded_at'], unique=False)
        batch_op.create_index('ix_metric_history_onu_type_time', ['onu_id', 'metric_type', 'recorded_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('target_roles', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_olt_category', ['olt_id', 'category'], unique=False)
        batch_op.create_index('ix_notifications_unread', ['is_read', 'resolved'], unique=False)

    op.create_table('olt_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Integer(), nullable=True),
    sa.Column('memory_usage', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.Integer(), nullable=True),
    sa.Column('total_ports', sa.Integer(), nullable=True),
    sa.Column('ports_up', sa.Integer(), nullable=True),
    sa.Column('ports_down', sa.Integer(), nullable=True),
    sa.Column('ports_shutdown', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olt_config_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('config_text', sa.Text(), nullable=False),
    sa.Column('config_size', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olt_sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('onu_count', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('sync_type', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('olt_sync_status', schema=None) as batch_op:
        batch_op.create_index('ix_olt_sync_status_olt_id', ['olt_id'], unique=False)

    op.create_table('onu_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('pon_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('max_tcont', sa.Integer(), nullable=True),
    sa.Column('max_gem', sa.Integer(), nullable=True),
    sa.Column('max_switch', sa.Integer(), nullable=True),
    sa.Column('max_flow', sa.Integer(), nullable=True),
    sa.Column('max_ip_host', sa.Integer(), nullable=True),
    sa.Column('max_veip', sa.Integer(), nullable=True),
    sa.Column('interfaces', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onu_vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('vlan_name', sa.String(length=100), nullable=True),
    sa.Column('vlan_type', sa.String(length=20), nullable=True),
    sa.Column('onu_profiles', sa.Text(), nullable=True),
    sa.Column('tagged_ports', sa.Text(), nullable=True),
    sa.Column('untagged_ports', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speed_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('profile_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type_val', sa.String(length=50), nullable=True),
    sa.Column('fixed_bandwidth', sa.String(length=50), nullable=True),
    sa.Column('assured_bandwidth', sa.String(length=50), nullable=True),
    sa.Column('max_bandwidth', sa.String(length=50), nullable=True),
    sa.Column('sir', sa.String(length=50), nullable=True),
    sa.Column('pir', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('onu_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_jobs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sync_jobs_olt_id', ['olt_id'], unique=False)

    op.create_table('tr069_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('acs_url', sa.String(length=256), nullable=True),
    sa.Column('acs_username', sa.String(length=100), nullable=True),
    sa.Column('acs_password', sa.String(length=512), nullable=True),
    sa.Column('default_olt_id', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('vlan_mode', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_log_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('port_type', sa.String(length=10), nullable=False),
    sa.Column('port_name', sa.String(length=50), nullable=False),
    sa.Column('rx_mbps_avg', sa.Float(), nullable=True),
    sa.Column('tx_mbps_avg', sa.Float(), nullable=True),
    sa.Column('rx_mbps_peak', sa.Float(), nullable=True),
    sa.Column('tx_mbps_peak', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('olt_id', 'port_type', 'port_name', 'hour_start', name='uq_traffic_hourly')
    )
    with op.batch_alter_table('traffic_log_hourly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_log_hourly_hour_start'), ['hour_start'], unique=False)

    op.create_table('traffic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('port_type', sa.String(length=10), nullable=False),
    sa.Column('port_name', sa.String(length=50), nullable=False),
    sa.Column('rx_mbps', sa.Float(), nullable=True),
    sa.Column('tx_mbps', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_logs_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('profile_image', sa.String(length=256), nullable=True),
    sa.Column('sidebar_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wan_ip_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('netmask', sa.String(length=50), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('dns1', sa.String(length=50), nullable=True),
    sa.Column('dns2', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ftth_odc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('otb_id', sa.Integer(), nullable=True),
    sa.Column('otb_core_number', sa.Integer(), nullable=True),
    sa.Column('total_cores', sa.Integer(), nullable=True),
    sa.Column('splitter_model', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['otb_id'], ['ftth_otb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ftth_pon_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('olt_name', sa.String(length=100), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('pon_name', sa.String(length=100), nullable=True),
    sa.Column('otb_id', sa.Integer(), nullable=True),
    sa.Column('otb_core_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.ForeignKeyConstraint(['otb_id'], ['ftth_otb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olt_pon_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('port_name', sa.String(length=50), nullable=True),
    sa.Column('port_interface', sa.String(length=50), nullable=True),
    sa.Column('admin_status', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('linktrap', sa.String(length=10), nullable=True),
    sa.Column('onu_count', sa.Integer(), nullable=True),
    sa.Column('onu_online', sa.Integer(), nullable=True),
    sa.Column('onu_offline', sa.Integer(), nullable=True),
    sa.Column('sfp_vendor', sa.String(length=50), nullable=True),
    sa.Column('sfp_type', sa.String(length=50), nullable=True),
    sa.Column('sfp_serial', sa.String(length=50), nullable=True),
    sa.Column('sfp_wavelength', sa.String(length=20), nullable=True),
    sa.Column('sfp_connector', sa.String(length=20), nullable=True),
    sa.Column('sfp_distance', sa.String(length=20), nullable=True),
    sa.Column('sfp_tx_power', sa.String(length=20), nullable=True),
    sa.Column('sfp_rx_power', sa.String(length=20), nullable=True),
    sa.Column('sfp_temperature', sa.String(length=20), nullable=True),
    sa.Column('sfp_voltage', sa.String(length=20), nullable=True),
    sa.Column('sfp_bias_current', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['olt_cards.id'], ),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('olt_pon_ports', schema=None) as batch_op:
        batch_op.create_index('ix_olt_pon_ports_olt_id', ['olt_id'], unique=False)

    op.create_table('olt_uplinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('port_name', sa.String(length=50), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('duplex', sa.String(length=10), nullable=True),
    sa.Column('medium', sa.String(length=20), nullable=True),
    sa.Column('admin_status', sa.String(length=10), nullable=True),
    sa.Column('oper_status', sa.String(length=10), nullable=True),
    sa.Column('line_protocol', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('negotiation', sa.String(length=10), nullable=True),
    sa.Column('flowcontrol', sa.String(length=10), nullable=True),
    sa.Column('switchport_mode', sa.String(length=20), nullable=True),
    sa.Column('vlans_tagged', sa.Text(), nullable=True),
    sa.Column('input_rate', sa.String(length=50), nullable=True),
    sa.Column('output_rate', sa.String(length=50), nullable=True),
    sa.Column('input_utilization', sa.String(length=20), nullable=True),
    sa.Column('output_utilization', sa.String(length=20), nullable=True),
    sa.Column('input_packets', sa.BigInteger(), nullable=True),
    sa.Column('output_packets', sa.BigInteger(), nullable=True),
    sa.Column('input_bytes', sa.BigInteger(), nullable=True),
    sa.Column('output_bytes', sa.BigInteger(), nullable=True),
    sa.Column('crc_errors', sa.Integer(), nullable=True),
    sa.Column('dropped', sa.Integer(), nullable=True),
    sa.Column('sfp_vendor', sa.String(length=100), nullable=True),
    sa.Column('sfp_serial', sa.String(length=100), nullable=True),
    sa.Column('sfp_type', sa.String(length=100), nullable=True),
    sa.Column('sfp_wavelength', sa.String(length=50), nullable=True),
    sa.Column('sfp_distance', sa.String(length=50), nullable=True),
    sa.Column('sfp_rx_power', sa.String(length=20), nullable=True),
    sa.Column('sfp_tx_power', sa.String(length=20), nullable=True),
    sa.Column('sfp_temperature', sa.String(length=20), nullable=True),
    sa.Column('sfp_voltage', sa.String(length=20), nullable=True),
    sa.Column('sfp_bias_current', sa.String(length=20), nullable=True),
    sa.Column('sfp_connector', sa.String(length=20), nullable=True),
    sa.Column('phy_attribute', sa.String(length=20), nullable=True),
    sa.Column('linktrap', sa.String(length=10), nullable=True),
    sa.Column('port_protect', sa.String(length=10), nullable=True),
    sa.Column('uplink_isolate', sa.String(length=10), nullable=True),
    sa.Column('port_type', sa.String(length=20), nullable=True),
    sa.Column('ip_vlan_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('ip_mask', sa.String(length=50), nullable=True),
    sa.Column('ip_gateway', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['olt_cards.id'], ),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('onu_index', sa.Integer(), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('pppoe', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('oper_state', sa.Integer(), nullable=True),
    sa.Column('reg_status', sa.Integer(), nullable=True),
    sa.Column('rx_power', sa.Float(), nullable=True),
    sa.Column('tx_power', sa.Float(), nullable=True),
    sa.Column('onu_rx_power', sa.Float(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('last_dereg_reason', sa.String(length=50), nullable=True),
    sa.Column('actual_type', sa.String(length=100), nullable=True),
    sa.Column('onu_type', sa.String(length=100), nullable=True),
    sa.Column('card', sa.String(length=20), nullable=True),
    sa.Column('pon', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('last_offline', sa.DateTime(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('wifi_config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onus', schema=None) as batch_op:
        batch_op.create_index('ix_onus_olt_id', ['olt_id'], unique=False)
        batch_op.create_index('ix_onus_olt_status', ['olt_id', 'status'], unique=False)
        batch_op.create_index('ix_onus_serial_number', ['serial_number'], unique=False)
        batch_op.create_index('ix_onus_status', ['status'], unique=False)

    op.create_table('ftth_odp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('odc_id', sa.Integer(), nullable=True),
    sa.Column('odc_core_number', sa.Integer(), nullable=True),
    sa.Column('total_ports', sa.Integer(), nullable=True),
    sa.Column('splitter_model', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['odc_id'], ['ftth_odc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onu_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onu_id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('onu_name', sa.String(length=150), nullable=True),
    sa.Column('onu_index', sa.String(length=30), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('dereg_reason', sa.String(length=50), nullable=True),
    sa.Column('rx_power', sa.Float(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.ForeignKeyConstraint(['onu_id'], ['onus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onu_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_onu_status_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_onu_status_history_new_status', ['new_status'], unique=False)
        batch_op.create_index('ix_onu_status_history_olt_id', ['olt_id'], unique=False)
        batch_op.create_index('ix_onu_status_history_onu_id', ['onu_id'], unique=False)

    op.create_table('ftth_odp_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odp_id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['odp_id'], ['ftth_odp.id'], ),
    sa.ForeignKeyConstraint(['onu_id'], ['onus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ftth_odp_port')
    with op.batch_alter_table('onu_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_onu_status_history_onu_id')
        batch_op.drop_index('ix_onu_status_history_olt_id')
        batch_op.drop_index('ix_onu_status_history_new_status')
        batch_op.drop_index('ix_onu_status_history_created_at')

    op.drop_table('onu_status_history')
    op.drop_table('ftth_odp')
    with op.batch_alter_table('onus', schema=None) as batch_op:
        batch_op.drop_index('ix_onus_status')
        batch_op.drop_index('ix_onus_serial_number')
        batch_op.drop_index('ix_onus_olt_status')
        batch_op.drop_index('ix_onus_olt_id')

    op.drop_table('onus')
    op.drop_table('olt_uplinks')
    with op.batch_alter_table('olt_pon_ports', schema=None) as batch_op:
        batch_op.drop_index('ix_olt_pon_ports_olt_id')

    op.drop_table('olt_pon_ports')
    op.drop_table('ftth_pon_port')
    op.drop_table('ftth_odc')
    op.drop_table('wan_ip_profiles')
    op.drop_table('users')
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_logs_recorded_at'))

    op.drop_table('traffic_logs')
    with op.batch_alter_table('traffic_log_hourly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_log_hourly_hour_start'))

    op.drop_table('traffic_log_hourly')
    op.drop_table('tr069_profiles')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_jobs_olt_id')
        batch_op.drop_index('ix_sync_jobs_created_at')

    op.drop_table('sync_jobs')
    op.drop_table('speed_profiles')
    op.drop_table('onu_vlans')
    op.drop_table('onu_types')
    with op.batch_alter_table('olt_sync_status', schema=None) as batch_op:
        batch_op.drop_index('ix_olt_sync_status_olt_id')

    op.drop_table('olt_sync_status')
    op.drop_table('olt_config_backups')
    op.drop_table('olt_cards')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_unread')
        batch_op.drop_index('ix_notifications_olt_category')

    op.drop_table('notifications')
    with op.batch_alter_table('metric_history', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_history_onu_type_time')
        batch_op.drop_index('ix_metric_history_olt_type_time')

    op.drop_table('metric_history')
    op.drop_table('maintenance_windows')
    op.drop_table('ftth_otb')
    op.drop_table('fans')
    op.drop_table('uptime_log')
    op.drop_table('templates')
    op.drop_table('system_config')
    op.drop_table('roles')
    op.drop_table('onu_custom_columns')
    op.drop_table('olts')
    op.drop_table('ftth_fiber_path')
    op.drop_table('bot_config')
    op.drop_table('alert_rules')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_history_onu_type')
        batch_op.drop_index('ix_alert_history_olt_type')

    op.drop_table('alert_history')
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_action_logs_user_id')
        batch_op.drop_index('ix_action_logs_created_at')
        batch_op.drop_index('ix_action_logs_category')

    op.drop_table('action_logs')
    # ### end Alembic commands ###
