"""add fibers_per_tube to ftth_otb and ftth_odc

Revision ID: 3c4612c99cab
Revises: 89a0f326f24c
Create Date: 2026-09-03 00:12:11.659442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4612c99cab'
down_revision = '89a0f326f24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_odc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fibers_per_tube', sa.Integer(), nullable=False, server_default='12'))

    with op.batch_alter_table('ftth_otb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fibers_per_tube', sa.Integer(), nullable=False, server_default='12'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_otb', schema=None) as batch_op:
        batch_op.drop_column('fibers_per_tube')

    with op.batch_alter_table('ftth_odc', schema=None) as batch_op:
        batch_op.drop_column('fibers_per_tube')

    # ### end Alembic commands ###
