"""add ftth JC (joint closure) + splice tables, feed_source on ODC/ODP

Revision ID: b0b167611fa0
Revises: 3c4612c99cab
Create Date: 2026-09-03 23:13:08.382559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b167611fa0'
down_revision = '3c4612c99cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftth_jc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('closure_type', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_cores', sa.Integer(), nullable=True),
    sa.Column('parent_type', sa.String(length=10), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ftth_jc_splice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jc_id', sa.Integer(), nullable=False),
    sa.Column('core_in', sa.Integer(), nullable=False),
    sa.Column('core_out', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jc_id'], ['ftth_jc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jc_id', 'core_out', name='uq_jc_core_out')
    )
    with op.batch_alter_table('ftth_odc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_source', sa.String(length=10), nullable=False, server_default='otb'))
        batch_op.add_column(sa.Column('jc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jc_core_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ftth_odc_jc_id', 'ftth_jc', ['jc_id'], ['id'])

    with op.batch_alter_table('ftth_odp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_source', sa.String(length=10), nullable=False, server_default='odc'))
        batch_op.add_column(sa.Column('jc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jc_core_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ftth_odp_jc_id', 'ftth_jc', ['jc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_odp', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ftth_odp_jc_id', type_='foreignkey')
        batch_op.drop_column('jc_core_number')
        batch_op.drop_column('jc_id')
        batch_op.drop_column('feed_source')

    with op.batch_alter_table('ftth_odc', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ftth_odc_jc_id', type_='foreignkey')
        batch_op.drop_column('jc_core_number')
        batch_op.drop_column('jc_id')
        batch_op.drop_column('feed_source')

    op.drop_table('ftth_jc_splice')
    op.drop_table('ftth_jc')
    # ### end Alembic commands ###
