"""add feed_source jc_id jc_core_number to ftth_otb and ftth_odp_port

Revision ID: ead46e8222d6
Revises: edfd5ab833df
Create Date: 2026-09-07 23:13:24.737374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead46e8222d6'
down_revision = 'edfd5ab833df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_otb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_source', sa.String(length=10), nullable=False, server_default='pon'))
        batch_op.add_column(sa.Column('jc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jc_core_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ftth_otb_jc_id', 'ftth_jc', ['jc_id'], ['id'])

    with op.batch_alter_table('ftth_odp_port', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_source', sa.String(length=10), nullable=False, server_default='direct'))
        batch_op.add_column(sa.Column('jc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jc_core_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ftth_odp_port_jc_id', 'ftth_jc', ['jc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_odp_port', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ftth_odp_port_jc_id', type_='foreignkey')
        batch_op.drop_column('jc_core_number')
        batch_op.drop_column('jc_id')
        batch_op.drop_column('feed_source')

    with op.batch_alter_table('ftth_otb', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ftth_otb_jc_id', type_='foreignkey')
        batch_op.drop_column('jc_core_number')
        batch_op.drop_column('jc_id')
        batch_op.drop_column('feed_source')

    # ### end Alembic commands ###
