"""add tube_in_label and tube_out_label to ftth_jc_splice

Revision ID: edfd5ab833df
Revises: afdc4c1cf4d4
Create Date: 2026-09-05 00:19:33.902721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfd5ab833df'
down_revision = 'afdc4c1cf4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_jc_splice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tube_in_label', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tube_out_label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_jc_splice', schema=None) as batch_op:
        batch_op.drop_column('tube_out_label')
        batch_op.drop_column('tube_in_label')

    # ### end Alembic commands ###
