"""add ftth_otb_port table

Revision ID: 89a0f326f24c
Revises: 2169e93c7970
Create Date: 2026-09-02 23:12:10.965584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a0f326f24c'
down_revision = '2169e93c7970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftth_otb_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otb_id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['otb_id'], ['ftth_otb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otb_id', 'port_number', name='uq_otb_port_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ftth_otb_port')
    # ### end Alembic commands ###
