"""add fibers_per_tube to ftth_jc

Revision ID: afdc4c1cf4d4
Revises: b0b167611fa0
Create Date: 2026-09-04 00:02:57.966797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdc4c1cf4d4'
down_revision = 'b0b167611fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_jc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fibers_per_tube', sa.Integer(), nullable=False, server_default='12'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ftth_jc', schema=None) as batch_op:
        batch_op.drop_column('fibers_per_tube')

    # ### end Alembic commands ###
